import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/redux-provider";
import { parseCookies } from "nookies";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        
      <div className="mt-100">
        <ReduxProvider > 
        {parseCookies().message === 'SUCCESS' && <Header/>}
          {children}</ReduxProvider>
        </div>
      </body>
    </html>
  );
}